### PR TITLE
fix ld64 build using gcc4.3 and gcc4.4

### PR DESCRIPTION
**Pull request by sezero**
ld64 fails building with gcc4.3 or gcc4.4. Here are the errors thrown
by gcc-4.4.7 on my ContOS-6.9:

```
./src/ld.cpp: In member function ‘void Linker::collectStabs(ObjectFile::Reader*, std::map<const ObjectFile::Atom*, unsigned int, std::less<const ObjectFile::Atom*>, std::allocator<std::pair<const ObjectFile::Atom* const, unsigned int> > >&)’:
./src/ld.cpp:2309: warning: format ‘%lu’ expects type ‘long unsigned int’, but argument 3 has type ‘size_t’
./src/ld.cpp: In member function ‘ObjectFile::Reader* Linker::createReader(const Options::FileInfo&)’:
./src/ld.cpp:2929: error: using ‘typename’ outside of template
./src/ld.cpp:2931: error: using ‘typename’ outside of template
./src/ld.cpp:2933: error: using ‘typename’ outside of template
./src/ld.cpp:2937: error: using ‘typename’ outside of template
./src/ld.cpp:2939: error: using ‘typename’ outside of template
./src/ld.cpp:2941: error: using ‘typename’ outside of template
./src/ld.cpp:2945: error: using ‘typename’ outside of template
./src/ld.cpp:2947: error: using ‘typename’ outside of template
./src/ld.cpp:2949: error: using ‘typename’ outside of template
./src/ld.cpp:2953: error: using ‘typename’ outside of template
./src/ld.cpp:2955: error: using ‘typename’ outside of template
./src/ld.cpp:2957: error: using ‘typename’ outside of template
./src/ld.cpp:2960: error: using ‘typename’ outside of template
./src/ld.cpp:2962: error: using ‘typename’ outside of template
./src/ld.cpp:2964: error: using ‘typename’ outside of template
```

This changeset fixes the build.  As far as I can see, one other forker
uses the same fix:
https://github.com/kevinxucs/xchain/commit/0910b5a3635ac16b5c2b23d2f8637ad1e70e8a88

Regards.

### CODE REVIEW

**Comment by Tatsh** [comment]
This is years ago but I recall adding the `typename` keyword to make this work, and this would probably be around the time of GCC 4.4. I'm on Gentoo and GCC is distributed a little differently on Ubuntu, so I'm wondering if a check is necessary, especially a feature check.

**Comment by sezero** [comment]
Well, I am not good at all with C++, so I'll leave it to you.
